# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

welcome=/WEB-INF/views/welcome.jsp
index=/index.jsp
sellersignin=/WEB-INF/views/sellersignin.jsp
signup=pixelmart.models.SignUpModel
signin=pixelmart.models.SignInModel
sellersignedin=pixelmart.models.SellerSignInModel
signedup=/WEB-INF/views/signedup.jsp
signinform=pixelmart.models.SignInFormModel

unreguser=/WEB-INF/views/unregistereduser.jsp
invalidpage=/WEB-INF/views/invalidpage.jsp
unverifiedusers=/WEB-INF/views/unverifiedusers.jsp


emailverifier=pixelmart.models.EmailVerifierModel
verified=/WEB-INF/views/verified.jsp
emailchecker=pixelmart.models.EmailCheckerModel


buyer=/WEB-INF/views/buyer.jsp
seller=/WEB-INF/views/seller.jsp

prodcat=pixelmart.models.ProductCategoryModel
prodsubcat=pixelmart.models.ProductSubcategoryModel
proddata=pixelmart.models.ProductDataModel
prodld=pixelmart.models.ProductLoadModel
pld=/WEB-INF/views/productld.jsp
proddisp=/WEB-INF/views/productdisplay.jsp

carsl=pixelmart.models.Carousel1Model
subcat=/WEB-INF/views/subcategories.jsp