# JSP Pages
welcome=/WEB-INF/views/welcome.jsp
index=/index.jsp
sellersignin=/WEB-INF/views/sellersignin.jsp
signedup=/WEB-INF/views/signedup.jsp

unreguser=/WEB-INF/views/unregistereduser.jsp
invalidpage=/WEB-INF/views/invalidpage.jsp
unverifiedusers=/WEB-INF/views/unverifiedusers.jsp
verified=/WEB-INF/views/verified.jsp

admin=/WEB-INF/views/admin.jsp
buyer=/WEB-INF/views/buyer.jsp
seller=/WEB-INF/views/seller.jsp

pld=/WEB-INF/views/productld.jsp
proddisp=/WEB-INF/views/productdisplay.jsp
subcat=/WEB-INF/views/subcategories.jsp


# Models
signup=pixelmart.models.SignUpModel
signin=pixelmart.models.SignInModel
sellersignedin=pixelmart.models.SellerSignInModel
signinform=pixelmart.models.SignInFormModel

emailverifier=pixelmart.models.EmailVerifierModel
emailchecker=pixelmart.models.EmailCheckerModel

prodcat=pixelmart.models.ProductCategoryModel
prodsubcat=pixelmart.models.ProductSubcategoryModel
produld=pixelmart.models.ProductUploadModel
prodld=pixelmart.models.ProductLoadModel
carsl=pixelmart.models.Carousel1Model

importprods=pixelmart.models.ImportProductsModel